//
//  GlobalStringConstant.swift
//  Should I Go
//
//  Created by Nasib Ali Ansari on 01/12/15.
//  Copyright © 2015 Nasib Ali Ansari. All rights reserved.
//

import UIKit




//let NABaseServerUrl                 = "http://lamp.trignodev.net/should_i_go/" // OLD
//let NABaseServerUrl                 = "http://sig.trignodev.net/should_i_go/" //closed by nitin
//let NABaseServerUrl              = "http://192.168.16.7/shouldigo-webservice.git/should_i_go/"
let NABaseServerUrl              = "http://lamp.trignodev.net/shouldigo/web/"
let NALoginEmailId                  = "email"
let NALoginPublicProfile            = "public_profile"
let NALoginEmailPassword            = "password"
let NALoginSource                   = "source"
let NALoginName                     = "name"
let NALoginUserName                 = "username"
let NAStatusKey                     = "status"
let NAFBRequestField                = "fields"
let NAServiceContentType            = "content-type"
let NAServiceContentTypeValue       = "application/json"
let NALoginApiKey                   = "login"
let NALoginSourceValue              = "fb"
let NABussinessNameKey              = "term"
let NABussinessLocationKey          = "ll"
let NASearchLocationApiKey          = "search_loc"
let NAAvgBusyRatingKey              = "average_busy"
let NAAvgMaleFemaleRatingKey        = "average_female_male_ratio"
let NAAvgHotnessRatingKey           = "average_hotness"
let NAAvgSeatingRatingKey           = "average_seating"
let NABusinessIdKey                 = "business_id"
let NABusinessHotSpotKey            = "hotspot"
let NABusinessNameKey               = "business_name"
let NABusinessImageUrlKey           = "business_image_url"
let NABusinessTextKey               = "business_text"
let NABusinessLatitudeKey           = "latitude"
let NABusinessLongitudeKey          = "longitude"
let NABusinessTotalLikeKey          = "total_like"
let NABusinessTotalDisLikeKey       = "total_dislike"
let NABusinessLikeDisLikeStatusKey  = "like_dislike_status"
let NAAvgRatingKey                  = "average_rating"
let NARecentRatingKey               = "recent_rating"
let NABusinessUserRatingKey         = "user_rating"
let NABusinesskey                   = "business"
let NABusinessGetRatingApi          = "get_rating"
let NAGetUserRatingDataKey          = "data"
let NAReviewId                      = "review_id"
let NAReviewText                    = "review_text"
let NAReviewDate                    = "date"
let NAReviewLikeStatus              = "likeStatus"
let NAReviewPhoto                   = "photo"
let NAReviewVideo                   = "video"
let NAReviewRatingsKey              = "ratings"
let NARatingKey                     = "rating"
let NABusinessRatingKey             = "business_rating"
let NABusinessReviewKey             = "businessReview"
let NABusyRatingKey                 = "busy"
let NAMaleFemaleRatingKey           = "female_male_ratio"
let NAHotnessRatingKey              = "hotness"
let NASeatingRatingKey              = "seating"
let NAResponseMessage               = "message"
let NASaveImageApi                  = "save_image"
let NASaveVedioApi                  = "save_video"
let NAImagekey                      = "image"
let NAVedioKey                      = "video"
let NALikeDisLikeApi                = "businessReviewld"
let NAThumbType                     = "thumbs_type"
let NARatingReviewIdKey             = "rating_and_review_id"
let NAUberAppURlString              = "uber:"
let NAUberWebURLString              = "http://m.uber.com"
let NASearchLimitKey                = "radius"
let NASearchBusinessNoKey           = "limit"
let NABusinessAddress               = "business_address"
let NABusinessLikePercent           = "like_percentage"
let NALatLong                       = "add_lat_lng"
let NAUserOfferApi                  = "user_offer"
let NAPageNumberKey                 = "page_id"
let NAOfferText                     = "offer_text"
let NAOfferId                       = "offer_id"
let NAOfferName                     = "offer_name"
let NAOfferStartDate                = "start_date"
let NAOfferEndDate                  = "end_date"
let NAOffersKey                     = "offers"
let NAOfferNextPage                 = "next_page"
let NAPushNotificationApi           = "send_device_token"
let NAPushNotificationDeviceToken   = "token"
let NAOSType                        = "ostype"
let NAUserDefaultBusinessKey        = "business"
let NAUserDefaultRadiusKey          = "radius"
let NARatingTimeKey                 = "rating_time"
let NARatingPointKey                = "points"
let NABusinessTermKey               = "business_term"
let NABusinessAddFavorite           = "current_user_fav"
let NABusinessRecentOffer           = "offer"
let NARegisterKey                   = "registration"
let NAPasswordKey                   = "password"

// Controller Segue name
let NAMapSegueName                  = "MapViewController"
let NACustomAlertView               = "CustomAlertViewController"
let NAOfferSeguename                = "offer_seque"

class GlobalStringConstant: NSObject {
}
